### ISSUE TITLE
Determine or document how to call clean PR action

### ISSUE THREAD

**Issue by hussainweb** [axelerant/platformsh-action#22]
Sometimes, a PR may not be deployed at all. For example, we don't deploy PRs created by Dependabot in contrib-tracker/backend. In this case, the clean PR workflow throws an error when such PRs are closed. It's not harmful (as there is nothing to delete in the first place), but the errors may be sore to our eyes.

Let's document how we should use this action to avoid those errors.

**Comment by zeshanziya** [comment]
So instead of throwing an error, we can just display a warning message setting `No active environment found`?

**Comment by zeshanziya** [comment]
Fixed in PR #26
